# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Site settings
title: HackLB
email: rogerhoward+hacklb@gmail.com
description: "Or, how I learned to stop waiting for others to open our data."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.hacklb.com" # the base hostname & protocol for your site

permalink: pretty


# Social media profiles - feel free to add more here
twitter_username: hacklongbeach
github_username:  hacklb
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://


# Address information
address_street:
address_city: Long Beach
address_state: CA
address_zip:

# Build settings
markdown: kramdown


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - .gitignore
  - .editorconfig
  - RAKEFILE
  - README.md
  - snips.md